### ISSUE TITLE
[Juno][Volta] Update Juno components to latest standards

### ISSUE THREAD

**Issue by edda** [sapcc/juno#389]
1. Some of the Juno components used to build the certificate form are deprecated and should be updated. See official documentation to check the wich components should be used:

- https://ui.juno.qa-de-1.cloud.sap/?path=/docs/forms-textarea--default
- https://github.com/sapcc/juno/blob/main/apps/volta/src/components/NewCertificateForm.js

ex: use the Textarea instead of TextareaRow or Textinput instead of TextInputRow

2. Switch the Checkbox within in a Stack and with a span to the new checkbox with attribute label since this is the new way to implement. The Stack is not needed anymore.

- https://github.com/sapcc/juno/blob/main/apps/volta/src/components/NewCertificateResults.js#L40

**Comment by TilmanHaupt** [comment]
Also added endless-scrolling
