### ISSUE TITLE
[Greenhouse] Fix plugin wrapper div styles so the layout works as designed

### ISSUE THREAD

**Issue by edda** [sapcc/juno#410]
In Greenhouse plugins are loaded into a wrapper div which misses the correct styles to make the page layout work as designed. What we want is for the plugin apps to take the full height even if there is not enough content to fill the full browser height. This is achieved by ensuring, that each wrapper div inbetween the plugin markup and the Greenhouse shell has `display: inline`.

**Comment by andypf** [comment]
all wrapper in between already have the class inline. I had to add h-full class to the greenhouse-main div
