### ISSUE TITLE
[Supernova][Doop] Change initial support group filter from team to new support group info

### ISSUE THREAD

**Issue by edda** [sapcc/juno#418]
For some people their team membership doesn't align with their support groups (e.g. there are multiple support groups in Team Core). For them the nice initial filter doesn't work which is annoying.

@uwe-mayer is currently working on adding the support group info to the token of the logged in user. Once this is done we should change our initial support group filter such that it takes the support group membership as value for the filter instead of the team.

This needs to be changed in Supernova and Doop.

**Comment by uwe-mayer** [comment]
[PR](https://github.wdf.sap.corp/cc/greenhouse/pull/242) is merged.
Who will add the necessary `greenhouse.sap/support-group` label for `ccloud`? @auhlig ?
