### ISSUE TITLE
[assets-overview]:  update Juno components to the latest standards (TextInputRow and SelectRow)

### ISSUE THREAD

**Issue by ArtieReus** [sapcc/juno#426]
When running the assets-overview App you can see following warning:
- SelectRow is deprecated and will be removed in future versions. To be future-proof, use Select instead.
- TextInputRow is deprecated and will be removed in future versions. To be future-proof, use TextInput instead.

**Comment by TilmanHaupt** [comment]
Also added endless-scroll
