### ISSUE TITLE
[url-state-provider] it seems that adding `#<any_value>` breaks the logic in the lib

### ISSUE THREAD

**Issue by ArtieReus** [sapcc/juno#476]
Example adding #12345 and after reloading the page:
- \[assets-overview]: https://assets.juno.qa-de-1.cloud.sap/?__s=(assets~Foverview:(assetName:dashboard,assetVersion:1.0.1,navItem:%27%27,panelOpened:++,panelTabIndex:+0,tabIndex:+1))
- \[greenhouse]: https://dashboard.greenhouse-qa.eu-nl-1.cloud.sap/?org=ccloud&__s=%28supernova%3A%28d%3A-+%2Cf%3A%28support%7ESgroup%3A%28containers%29%29%2Cp%3Aprod%2Cs%3A%27%27%29%29#12345

The page remains empty because this error breaks everything.

Assumption: the `#` breaks the json transpile logic of the URL state

Fix:
1. This shouldn't break the app (probably needs some try/catch)
2. We need to enhance the parser so it can handle `#`

**Comment by andypf** [comment]
This issue is no longer relevant because it has been addressed in a newer version. Please refer to the [latest release](https://github.com/cloudoperators/juno/tree/main/packages/url-state-provider) for the updated functionality. If you continue to experience problems, feel free to open a new issue.
