### ISSUE TITLE
[Teams-admin] Fixes/Changes for Management apps

### ISSUE THREAD

**Issue by ArtieReus** [sapcc/juno#486]
- \[teams]: 
- [x] There are no errors shown to the user if no login succeed or login not done. Just a black window. Check if `loggedIn` and if not, then display a message to the user. See Supernova or doop as example.
- [x] display errors from api client. If API client has errors show the error code and error message to the user in a `Message` component
- [x] embedded prop is not implemented correctly. The `embedded` prop can be string or boolean (depending on where it comes from. So the current check: `{props.embedded === false}` doesn't work as expected because String `false` is not strictly equal to boolean `false`, `"false" !== false`. See juno template app for example how to fix the expression
- [x] Store state (e.g. which team was selected) in URL and also read from URL when loading. See Supernova/Doop `useUrlState` hook.
- [x] Remove teams side navigation, instead add a filter section (similar to supernova) where teams can be selected from a Select box
- [ ] Implement a mock if you want to visualize anything. If not, we'll need to use a real login in the management app, being careful not to commit it accidentally
- [x] add endless scroll feature to team member list (automatic loading of more entries when user scrolls down). See Supernova alerts list for how this is done

**Comment by edda** [comment]
Done. See here: https://github.wdf.sap.corp/cc/greenhouse/issues/54

**Comment by ArtieReus** [comment]
https://github.wdf.sap.corp/cc/greenhouse/tree/main/ui/team-admin
