### ISSUE TITLE
[CI] Fix vulnerable base images

### ISSUE THREAD

**Issue by andypf** [sapcc/juno#530]
Check the doop dashboard for vulnerable images. We have issues in all our deployments

**Comment by andypf** [comment]
https://github.wdf.sap.corp/cc/base-images

**Comment by edda** [comment]
- [ ] Elektra
- [ ] Supernova (standalone)
- [ ] Cypress Dashboard
- [ ] Juno UI Storybook
- [ ] Workspaces
