### ISSUE TITLE
[greenhouse-mgmt] Create PluginConfig plugin

### ISSUE THREAD

**Issue by edda** [sapcc/juno#539]
Create a "PluginAdmin" plugin for the greenhouse management area which will show installed/configured plugins and available (not yet installed/configured) plugins. Eventually this plugin will also allow de-/activation and configuration of plugins.

First steps:

- [x] Create a new ui plugin in `greenhouse/ui` (as an external Juno app)
- [x] Ensure the new plugin is built by a pipeline
- [x] Add plugin to greenhouse-management side navigation
- [x] plugin needs auth and k8sclient

Plugin first steps:
- [x] use k8sclient to load all available `pluginconfig` resources and render a list of them
- [x] for each pluginconfig items in list add a details view (opens in `Panel`) which at first displays the pluginconfig in a `JSONView` (see Supernova AlertDetails as inspiration)
- [x] Check which metadata makes sense to extract specifically from the JSON to display in the list view  and in the details view in a key/value type section (similar to Supernova AlertDetails)

**Comment by ArtieReus** [comment]
This is the way how to retrieve the exposedServices from the plugin configs:
```
kc greenhouse-qa
kn ccloud
k get pluginconfig kube-moni-ext -o json

{
    "apiVersion": "greenhouse.sap/v1alpha1",
    "kind": "PluginConfig",
    ...
    "status": {
        "description": "Native deployment and management of Prometheus along with Kubernetes cluster monitoring components.",
        "exposedServices": {
            "https://kube-moni-ext-prometheus--ccloud--monitoring.ccloud.greenhouse-qa.eu-nl-1.cloud.sap": {
                "name": "kube-moni-ext-prometheus",
                "namespace": "ccloud",
                "port": 9090
            }
        },
        ...
    }
}
```

**Comment by andypf** [comment]
This package was moved to cloudoperators/juno
