### ISSUE TITLE
[oauth] Fix mock prop handling when its false

### ISSUE THREAD

**Issue by hodanoori** [sapcc/juno#553]
Example: In team-admin project, where the auth app is imported from widget loader, I added this prop to handle mocking auth object. But it does not work properly when its value false is. For now I added the following lines with the extra check into index.html in this project. After fixing this issue in auth app, team-admin should be adjusted accordingly.

allProps?.appProps?.isMock
        ? authScript.setAttribute(
            "data-props-mock",
            `${allProps?.appProps?.isMock}`
          )
        : null

**Comment by andypf** [comment]
outdated
