### ISSUE TITLE
[Juno] Template app: Clean up

### ISSUE THREAD

**Issue by edda** [sapcc/juno#555]
Add `ErrorBoundary` to template app

**Comment by ArtieReus** [comment]
1. Remove test SVGs and GIFs from https://github.com/sapcc/juno/tree/main/apps/template/src/assets
2. Remove Styles from https://github.com/sapcc/juno/blob/main/apps/template/src/styles.scss#L9
3. Maybe initially store everything in a single file without slices at https://github.com/sapcc/juno/blob/main/apps/template/src/lib/store/createGlobalsSlice.js
4. Set URL_STATE_KEY as the default value in the store at https://github.com/sapcc/juno/blob/main/apps/template/src/App.js#L32
5. Perhaps leave only "Hello world" at https://github.com/sapcc/juno/blob/main/apps/template/src/AppContent.js#L13
