### ISSUE TITLE
[juno-ui-components] DatePicker clicking on calendar icon reopens the panel

### ISSUE THREAD

**Issue by hodanoori** [sapcc/juno#578]
In the new key manager in Elektra, the DateTimePicker is used within a PanelBody with a Form below it. In this scenario, the calendar opens correctly when I click anywhere except on the calendar icon. However, when I click on the calendar icon, the panel closes and then reopens and this should be fixed.

**Comment by TilmanHaupt** [comment]
This also happens in a normal Panel in Juno.
