### ISSUE TITLE
[supernova] UI bug in Scheduled Silences >>> DatePicker

### ISSUE THREAD

**Issue by TilmanHaupt** [sapcc/juno#610]
The DatePicker has a problem in the Scheduled Silence Modal inside greenhouse. The DatePicker opens outside the shown parts of the Modal so you need to scroll to the right. This just happens if the modal get very small. I dont know how to solve the issue. Thanks. 👍 

![Image](https://github.com/sapcc/juno/assets/147151040/ffee9d4e-d8c9-45ec-a4ca-f2586ebb7661)
![Image](https://github.com/sapcc/juno/assets/147151040/91daf131-078f-48f8-a226-ce70e383baac)
![Image](https://github.com/sapcc/juno/assets/147151040/3c6e7b31-6af2-4766-a862-9ecc189c6ec4)

**Comment by edda** [comment]
@TilmanHaupt can you try to change this that instead of having two separate datepicker instances to use one with the range feature?

**Comment by TilmanHaupt** [comment]
The Layout of the range mode makes it not possible for me to define a start and endtime 

![Image](https://github.com/sapcc/juno/assets/147151040/dd44c33a-28d4-4a41-965c-ddd64c84aa4c)

**Comment by andypf** [comment]
supernova was moved to cloudoperators/juno
