### ISSUE TITLE
fix(juno): Assets Server does not contain newer versions of LimesUI

### ISSUE THREAD

**Issue by andypf** [sapcc/juno#634]
The Assets Server is currently not updated with the latest versions of LimesUI. As a result, the limes MFE in elektra can't be updated.

**Comment by VoigtS** [comment]
To clarify this issue, the definition of what version is marked as "latest" is broken in the pipeline. It seems like the last version that gets processed by the pipeline will be insertet as "latest" into the asset server.
This is how it looked like when the latest versioning worked:
`DIR: /tmp/latest/apps/limesUI@1.2.6
ASSET_PATH: apps
============
[...]
============
DIR: /tmp/latest/apps/limesUI@1.3.1`

This is how it currently looks like
`DIR: /tmp/latest/apps/limesUI@1.3.2
ASSET_PATH: apps
============
[...]
============
DIR: /tmp/latest/apps/limesUI@1.2.6
ASSET_PATH: apps`

The old version 1.2.6 is marked as "latest" in the asset server.

**Comment by andypf** [comment]
The issue was resolved by correcting the order of uploaded versions in the Swift container.
